import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  scroll: { padding: 20, paddingBottom: 48 },
  back: { color: colors.primary, fontWeight: "800", marginBottom: 22 },
  title: { color: colors.textPrimary, fontSize: 27, fontWeight: "900" },
  subtitle: {
    color: colors.textSecondary,
    lineHeight: 20,
    marginTop: 7,
    marginBottom: 18,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "900",
    marginTop: 20,
    marginBottom: 10,
  },
  label: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 7,
  },
  field: { marginBottom: 13 },
  input: {
    minHeight: 50,
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: 10,
    paddingHorizontal: 14,
  },
  multiline: { minHeight: 100, paddingTop: 13, textAlignVertical: "top" },
  selectorWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  selector: {
    minHeight: 43,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 11,
  },
  selectorActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  selectorText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "800",
  },
  selectorTextActive: { color: colors.white },
  locationButton: {
    minHeight: 52,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  locationText: { color: colors.primary, fontWeight: "800" },
  locationBadge: {
    color: colors.safe,
    backgroundColor: `${colors.safe}20`,
    borderRadius: 10,
    padding: 12,
    marginTop: 10,
    fontSize: 12,
    fontWeight: "800",
  },
  boundaryText: { color: colors.textSecondary, fontSize: 12, marginTop: 9 },
  uploadRow: { flexDirection: "row", gap: 10, marginTop: 12 },
  uploadButton: {
    flex: 1,
    minHeight: 58,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 7,
  },
  uploadText: { color: colors.primary, fontWeight: "800" },
  previewWrap: {
    marginTop: 14,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.surface,
  },
  preview: { width: "100%", height: 190, backgroundColor: colors.input },
  remove: {
    position: "absolute",
    right: 9,
    top: 9,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.danger,
    alignItems: "center",
    justifyContent: "center",
  },
  previewCaption: { color: colors.textSecondary, fontSize: 12, padding: 10 },
  cameraPreview: {
    minHeight: 250,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: colors.surface,
    gap: 10,
  },
  camera: { height: 220, width: "100%" },
  proofReady: {
    padding: 14,
    borderRadius: 11,
    backgroundColor: `${colors.safe}18`,
    gap: 10,
  },
  mediaRow: {
    minHeight: 44,
    marginTop: 8,
    paddingHorizontal: 12,
    borderRadius: 9,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  verificationPanel: {
    marginTop: 18,
    padding: 14,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  verificationRow: {
    minHeight: 34,
    alignItems: "center",
    flexDirection: "row",
    gap: 9,
  },
  verificationIcon: {
    width: 24,
    color: colors.safe,
    fontWeight: "900",
    textAlign: "center",
  },
  success: { color: colors.safe, fontWeight: "900", marginTop: 12 },
  error: {
    color: colors.danger,
    fontSize: 12,
    lineHeight: 18,
    marginVertical: 14,
  },
  status: {
    minHeight: 52,
    borderRadius: 11,
    backgroundColor: `${colors.primary}18`,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 9,
  },
  statusText: { color: colors.primary, fontWeight: "800" },
});
