import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { padding: 20, paddingBottom: 100, flexGrow: 1 },
  eyebrow: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  title: {
    color: colors.textPrimary,
    fontSize: 27,
    fontWeight: "900",
    marginTop: 5,
  },
  subtitle: { color: colors.textSecondary, marginTop: 7, marginBottom: 20 },
  error: { color: colors.danger, fontSize: 12, marginBottom: 12 },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: 14,
    overflow: "hidden",
    marginBottom: 13,
  },
  thumbnail: { height: 150, width: "100%", backgroundColor: colors.input },
  cardBody: { padding: 14 },
  cardTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  cardTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "900",
    flex: 1,
  },
  category: { color: colors.primary, fontSize: 11, fontWeight: "900" },
  location: { color: colors.textSecondary, marginTop: 6, fontSize: 13 },
  price: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "900",
    marginTop: 11,
  },
  priceUnit: { color: colors.textSecondary, fontSize: 11, fontWeight: "500" },
  badgeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    gap: 8,
  },
  documentBadge: {
    color: colors.textSecondary,
    backgroundColor: colors.input,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: 11,
    fontWeight: "800",
  },
  status: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  statusVerified: { backgroundColor: `${colors.safe}20` },
  statusPending: { backgroundColor: `${colors.warning}20` },
  statusText: { fontSize: 10, fontWeight: "800" },
  fab: {
    position: "absolute",
    right: 22,
    bottom: 22,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
  },
  empty: { paddingTop: 80, alignItems: "center" },
  emptyText: {
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: 20,
    maxWidth: 260,
  },
});
