import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  scroll: { padding: 20, paddingBottom: 40 },
  back: { color: colors.primary, fontWeight: "800", marginBottom: 18 },
  title: {
    color: colors.textPrimary,
    fontSize: 25,
    fontWeight: "900",
    marginTop: 18,
  },
  location: { color: colors.textSecondary, marginTop: 6 },
  badgeRow: { flexDirection: "row", gap: 8, marginTop: 13 },
  badge: { borderRadius: 16, paddingHorizontal: 10, paddingVertical: 6 },
  badgeText: { fontSize: 11, fontWeight: "900" },
  price: {
    color: colors.textPrimary,
    fontSize: 21,
    fontWeight: "900",
    marginTop: 16,
  },
  grid: { flexDirection: "row", gap: 10, marginTop: 15 },
  stat: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  statLabel: { color: colors.textSecondary, fontSize: 11 },
  statValue: { color: colors.textPrimary, fontWeight: "800", marginTop: 4 },
  section: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: "900",
    marginTop: 24,
    marginBottom: 11,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: 15,
  },
  plotLine: { color: colors.textSecondary, fontSize: 13, marginTop: 8 },
  plotStatus: {
    color: colors.safe,
    fontSize: 13,
    fontWeight: "900",
    marginTop: 13,
  },
  sellerRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: `${colors.primary}33`,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: colors.primary, fontSize: 17, fontWeight: "900" },
  sellerName: { color: colors.textPrimary, fontSize: 15, fontWeight: "900" },
  verified: {
    color: colors.safe,
    fontSize: 11,
    fontWeight: "800",
    marginTop: 4,
  },
  contact: { color: colors.textSecondary, marginTop: 15, fontSize: 13 },
  buttonRow: { flexDirection: "row", gap: 9, marginTop: 15 },
  contactButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 9,
    backgroundColor: colors.input,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  contactText: { color: colors.primary, fontWeight: "800", fontSize: 12 },
  coordinates: { color: colors.textSecondary, fontSize: 12, marginTop: 10 },
  note: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 10,
  },
  mapButton: { marginTop: 15 },
  escrow: { marginTop: 15, backgroundColor: colors.safe, borderRadius: 11 },
  media: {
    width: "100%",
    height: 190,
    marginTop: 10,
    borderRadius: 10,
    backgroundColor: colors.input,
  },
  mediaLink: {
    minHeight: 46,
    marginTop: 10,
    borderRadius: 10,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  mediaLinkText: { color: colors.primary, fontWeight: "800" },
});
